# Read the Docs configuration file for MkDocs projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: 'ubuntu-22.04'
  tools:
    python: '2.7'
  jobs:
    pre_build:
    - 'sed -i "s/__VERSION__/${READTHEDOCS_VERSION}/g" docs/*.md'

mkdocs:
  configuration: 'mkdocs.yml'
python:
  install:
  - requirements: 'docs/requirements.txt'
